---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: imagery-standardise-
spec:
  serviceAccountName: workflow-runner-sa
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: uri
        value: "s3://linz-imagery-staging/test/sample/"
      - name: filter
        value: "BX24_5000_0405.tif"
      - name: output
        value: "s3://linz-imagery-staging/test/sample-output/"
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list
            arguments:
              parameters:
                - name: uri
                  value: "{{workflow.parameters.uri}}"
                - name: filter
                  value: "{{workflow.parameters.filter}}"
          - name: standardise
            template: standardise
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
                - name: output
                  value: "{{workflow.parameters.output}}"
            depends: "aws-list"
            withParam: "{{tasks.aws-list.outputs.parameters.files}}"
    - name: aws-list
      inputs:
        parameters:
          - name: uri
          - name: filter
      container:
        image: ghcr.io/linz/basemaps/cli:v6.29.0-3-gb4dec98c
        command: [node, index.cjs]
        args: ["-V", "list", "--filter", "{{inputs.parameters.filter}}","--group", "10", "--output", "/tmp/file_list.json", "--config", "linz-bucket-config", "{{inputs.parameters.uri}}"]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: standardise
      inputs:
        parameters:
          - name: file
          - name: output
      container:
        image: ghcr.io/linz/topo-imagery:v0.2.0-4-gfd60e53
        command:
          - python
          - "/app/standardising.py"
        args:
          - "--source"
          - "{{inputs.parameters.file}}"
          - "--destination"
          - "{{inputs.parameters.output}}"
